

services:
  db:
    image: postgres:16
    container_name: proyecto_medico_db
    restart: always
    environment:
      POSTGRES_DB: clinica
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      # Datos persistentes de PostgreSQL
      - postgres_data:/var/lib/postgresql/data
      # Carpeta con tus scripts SQL de inicializaci√≥n
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d clinica"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: proyecto_medico_backend
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: backend_api.settings
      DB_NAME: clinica
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  
volumes:
  postgres_data:
